//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int ID_ADMINISTRADOR { get; set; }
        public string NOMBRE_USUARIO_ADMINISTRADOR { get; set; }
        public string PASSWORD_USUARIO_ADMINISTRADOR { get; set; }
        public string TIPO_CUENTA { get; set; }
    }
}
