//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicanteXOferta
    {
        public int FK_ID_OFERTA { get; set; }
        public int FK_ID_APLICANTE { get; set; }
        public System.DateTime FECHA_APLICACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual OfertasLaborale OfertasLaborale { get; set; }
    }
}
