//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplicante()
        {
            this.CapacitacionesXAplicantes = new HashSet<CapacitacionesXAplicante>();
            this.EducacionFormalXAplicantes = new HashSet<EducacionFormalXAplicante>();
            this.ExperienciaLaboralXAplicantes = new HashSet<ExperienciaLaboralXAplicante>();
            this.IdiomaXAplicantes = new HashSet<IdiomaXAplicante>();
            this.ReferenciasXAplicantes = new HashSet<ReferenciasXAplicante>();
            this.AplicanteXOfertas = new HashSet<AplicanteXOferta>();
        }
    
        public int ID_APLICANTE { get; set; }
        public int IDENTIFICACION { get; set; }
        public int FK_ID_TIPO_IDENTIFICACION { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string NOMBRE { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public int FK_ID_PAIS_NACIMIENTO { get; set; }
        public int FK_ID_NACIONALIDAD { get; set; }
        public int FK_ID_PAIS_RESIDENCIA { get; set; }
        public string DIRECCION { get; set; }
        public string PROVINCIA { get; set; }
        public string SEXO { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string NUMERO_CARNE { get; set; }
        public int FK_ID_TIPO_APLICANTE { get; set; }
        public string ESTADO_APLICANTE { get; set; }
        public string DESCRIPCION_CONOCIMIENTOS { get; set; }
        public Nullable<int> FK_ID_CUENTA_USUARIO { get; set; }
    
        public virtual Nacionalidade Nacionalidade { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual CuentasUsuario CuentasUsuario { get; set; }
        public virtual TipoAplicante TipoAplicante { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapacitacionesXAplicante> CapacitacionesXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducacionFormalXAplicante> EducacionFormalXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaLaboralXAplicante> ExperienciaLaboralXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaXAplicante> IdiomaXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciasXAplicante> ReferenciasXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicanteXOferta> AplicanteXOfertas { get; set; }
    }
}
