//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinadoresEscuela
    {
        public int ID_ESCUELA { get; set; }
        public string NOMBRE_ESCUELA { get; set; }
        public string NOMBRE_COORDINADOR { get; set; }
        public string EMAIL_COORDINADOR { get; set; }
        public string TELEFONO_COORDINADOR { get; set; }
    }
}
