//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.OfertasLaborales = new HashSet<OfertasLaborale>();
            this.SectoresProductivos = new HashSet<SectoresProductivo>();
        }
    
        public int ID_EMPRESA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string CEDULA_JURIDICA_EMPRESA { get; set; }
        public string DIRECCION_EMPRESA { get; set; }
        public string PROVINCIA_EMPRESA { get; set; }
        public int FK_ID_PAIS { get; set; }
        public string TELEFONO_EMPRESA { get; set; }
        public string EMAIL_EMPRESA { get; set; }
        public string DIRECCION_WEB_EMPRESA { get; set; }
        public string NOMBRE_CONTACTO_EMPRESA { get; set; }
        public string EMAIL_CONTACTO_EMPRESA { get; set; }
        public string CARGO_CONTACTO_EMPRESA { get; set; }
        public string TELEFONO_CONTACTO_EMPRESA { get; set; }
        public string DESC_ACTIVIDADES_EMPRESA { get; set; }
        public string ESTADO_EMPRESA { get; set; }
        public Nullable<int> FK_ID_CUENTA_USUARIO { get; set; }
    
        public virtual CuentasUsuario CuentasUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfertasLaborale> OfertasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectoresProductivo> SectoresProductivos { get; set; }
    }
}
