//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboralXAplicante
    {
        public int FK_ID_APLICANTE { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string NOMBRE_PUESTO { get; set; }
        public string ANNO_DESDE { get; set; }
        public string ANNO_HASTA { get; set; }
        public int FK_ID_PAIS_TRABAJO { get; set; }
    
        public virtual Aplicante Aplicante { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
