//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechasImportante
    {
        public int ID_FECHA_IMPORTANTE { get; set; }
        public string FECHA { get; set; }
        public string NOMBRE_ACTIVIDAD { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
