//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdiomaXAplicante
    {
        public int FK_ID_APLICANTE { get; set; }
        public int FK_ID_IDIOMA { get; set; }
        public int FK_ID_DOMINIO_LECTURA { get; set; }
        public int FK_ID_DOMINIO_ESCRITURA { get; set; }
        public int FK_ID_DOMINIO_ORAL { get; set; }
    
        public virtual Aplicante Aplicante { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual NivelDominioIdioma NivelDominioIdioma { get; set; }
        public virtual NivelDominioIdioma NivelDominioIdioma1 { get; set; }
        public virtual NivelDominioIdioma NivelDominioIdioma2 { get; set; }
    }
}
