//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelDominioIdioma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NivelDominioIdioma()
        {
            this.IdiomaXAplicantes = new HashSet<IdiomaXAplicante>();
            this.IdiomaXAplicantes1 = new HashSet<IdiomaXAplicante>();
            this.IdiomaXAplicantes2 = new HashSet<IdiomaXAplicante>();
        }
    
        public int ID_NIVEL_DOMINIO { get; set; }
        public string NOMBRE_NIVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaXAplicante> IdiomaXAplicantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaXAplicante> IdiomaXAplicantes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaXAplicante> IdiomaXAplicantes2 { get; set; }
    }
}
