//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoTECDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciasXAplicante
    {
        public int FK_ID_APLICANTE { get; set; }
        public string NOMBRE_EMPRESA_REFERENTE { get; set; }
        public string NOMBRE_REFERENTE { get; set; }
        public string PUESTO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual Aplicante Aplicante { get; set; }
    }
}
